name: Continuous integration
on: [push, pull_request]
env:
  NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/1697b7d480449b01111e352021f46e5879e47643.tar.gz
  ghc-exe: $(pwd)/ghc@580d39a221/bin/ghc

jobs:
  cabal-test-bench:
    name: Run tests & benchmarks with cabal
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build Nix dependencies
      run: nix-shell --pure --run "echo '=== Nix dependencies installed ==='"
    - name: Install custom GHC
      run: nix-shell --pure --run "tar xJf ghc-bindist@580d39a221.tar.xz && mkdir -p ghc@580d39a221 && cd ghc-9.9.20230911-x86_64-unknown-linux && ./configure --prefix="'$'"(pwd)/../ghc@580d39a221 && make install && cd .."
    - name: Init Cabal's config file
      run: nix-shell --pure --run "cabal --config-file=$HOME/.cabal/config user-config -f init"
    - name: Update Cabal's database
      run: nix-shell --pure --run "cabal update"
    - name: Build Cabal's dependencies
      run: nix-shell --pure --run "cabal build -w ${{ env.ghc-exe }} --allow-newer --disable-tests --disable-benchmarks --dependencies-only"

    - name: test:test target - build tests
      run: nix-shell --pure --run "cabal build -w ${{ env.ghc-exe }} --allow-newer linear-dest:test:test"
    - name: test:test target - run tests
      run: nix-shell --pure --run "cabal test -w ${{ env.ghc-exe }} --allow-newer linear-dest:test:test --test-options='+RTS -N1 -RTS' --test-show-details=streaming 2>&1 | tee test_results.txt"

    - name: bench:bench target - build benchmark
      run: nix-shell --pure --run "cabal build -w ${{ env.ghc-exe }} --allow-newer linear-dest:bench:bench"
    - name: bench:bench target - run benchmarks with -T
      run: nix-shell --pure --run "echo $'\n\n=== Benchmarks -T ===\n\n' > benchmark_results.txt && cabal bench -w ${{ env.ghc-exe }} --allow-newer linear-dest:bench:bench --benchmark-options='+RTS -T -N1 -RTS' 2>&1 | tee -a benchmark_results.txt"
    - name: bench:bench target - run benchmarks with -T in isolation
      run: nix-shell --pure --run "echo $'\n\n=== Benchmarks -T (isolation) ===\n\n' >> benchmark_results.txt &&  cabal run -w ${{ env.ghc-exe }} --allow-newer -v0 linear-dest:bench:bench -- -l | grep -P 'All\.[^\.]+\.benchmark\.' | while read -r name; do cabal run -w ${{ env.ghc-exe }} --allow-newer -v0 linear-dest:bench:bench -- -p '"'$'"0 == \"'\""'$'"name\"'\"' --csv temp.csv +RTS -T -N1 -RTS 2>&1 && tee -a benchmark_results.txt < <(tail -n1 temp.csv); done && rm temp.csv"
  
    - name: bench:bench target - single runs with -s
      run: nix-shell --pure --run "echo $'\n\n=== Single runs with -s (isolation) ===\n\n' >> benchmark_results.txt &&  cabal run -w ${{ env.ghc-exe }} --allow-newer -v0 linear-dest:bench:bench -- -l | grep -P 'All\.[^\.]+\.benchmark\.' | while read -r name; do echo $'\n\n=== Benchmark '\""'$'"name\"$' ===\n\n' | tee -a benchmark_results.txt && cabal run -w ${{ env.ghc-exe }} --allow-newer -v0 linear-dest:bench:bench -- "'$'"name +RTS -s -N1 -RTS 2>&1 | tee -a benchmark_results.txt ; done"

    - name: bench:bench target - build -p profiling
      run: nix-shell --pure --run "cabal build -w ${{ env.ghc-exe }} --allow-newer --enable-profiling --profiling-detail=late linear-dest:bench:bench"
    - name: bench:bench target - run -p profiling
      run: nix-shell --pure --run "mkdir -p prof && cabal run -w ${{ env.ghc-exe }} --allow-newer --enable-profiling --profiling-detail=late -v0 linear-dest:bench:bench -- -l | grep -P 'All\.[^\.]+\.benchmark\.' | while read -r name; do cabal run -w ${{ env.ghc-exe }} --allow-newer --enable-profiling --profiling-detail=late -v0 linear-dest:bench:bench -- "'$'"name +RTS -p -N1 -RTS 2>&1 && mv bench.prof \"prof/"'$'"name.prof\" ; done"

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: linear-dest
        path: |
          test_results.txt
          benchmark_results.txt
          prof
          ./dist-newstyle/build/x86_64-linux/ghc-9.9.20230911/linear-dest-0.2.0/build/**/*.dump-simpl
        retention-days: 30
